FROM node:18-alpine

WORKDIR /app

# Копирование package файлов
COPY package*.json ./
RUN npm install

# Копирование исходного кода
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]



